[package]
name = "eth_gas_tracker"
version = "0.1.0"
edition = "2021"
authors = ["Giorgi Abuladze (https://abula.dev)"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
